name: Build and Deploy to Rancher

env:
  DOCKER_USERNAME: ieielil
  DOCKER_PASSWORD: '@@rosalieamber##'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t hc-ci-cd:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker image tag hc-ci-cd:latest ieielil/hc-ci-cd:latest
          docker push ieielil/hc-ci-cd:latest

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-southeast-1 # Set your AWS region
        env:
         AWS_DEFAULT_REGION: ap-southeast-1
        
      - name: Authenticate with EKS
        run: aws eks update-kubeconfig --name eks-test
