name: Basic CI/CD ( Pipeline )

env:
  DOCKER_USERNAME: ieielil #DockerUsername
  DOCKER_PASSWORD: '' #DockerPassword

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

<<<<<<< HEAD
      - name: Build Docker image ( hc-ci-cd:latest ) #Image Name that you created in docker
=======
      - name: Determine Version
        id: semver
        run: |
          currentVersion="0.0.0"
          commitMessage=$(git log -1 --pretty=%B)

          if [[ $commitMessage =~ ^minor: ]]; then
            currentVersion=$(npm version minor)
          elif [[ $commitMessage =~ ^release: ]]; then
            currentVersion=$(npm version patch)
          elif [[ $commitMessage =~ ^major: ]]; then
            currentVersion=$(npm version major)
          fi

          echo "Current Version: $currentVersion"

      - name: Increment Git Tag
        run: |
          newTag=$(git describe --abbrev=0 --tags)
          git tag -a $newTag -m "Version $newTag"
          git push origin $newTag

      - name: Build Docker image
>>>>>>> cc83ca5b72b1606edac8d0e3cd52ec7f361c4ff2
        run: |
          docker build -t hc-ci-cd:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker image tag hc-ci-cd:latest ieielil/hc-ci-cd:latest
          docker push ieielil/hc-ci-cd:latest

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} #Replace with your access key id
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} #Replace with your access key
          aws configure set default.region ap-southeast-1 # Set your AWS region
        env:
         AWS_DEFAULT_REGION: ap-southeast-1

        - name: Create EKS Cluster
          run: |
          eksctl create cluster --name=eks-test --nodes=1 --region=ap-southeast-1 #--profile=kst-dev
        
      - name: Authenticate with EKS ( Authentication to eks cluster )
        run: aws eks update-kubeconfig --name eks-test

      - name: Deploy to EKS ( Deploying simple python app )
        run: | 
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout restart deploy/ci-cd-hc-app
